#!/usr/bin/env python3
"""Generate stimulus for tb_sha512_system.sv (full-system stress test).

Outputs (in the current directory):
  stress_mem.hex    : emulated HPS DDR3 image, one 64-bit little-endian word per line
                      (descriptor queues + document bytes)
  stress_docs.hex   : per document, one line: {job_id[15:0], len[31:0], addr[31:0]}
  stress_digest.hex : per document, the hashlib SHA-512 digest (512 bit, H0..H7)
  stress_sets.svh   : document index ranges and descriptor queue bases per test set

Golden model: Python hashlib.
"""
import hashlib, random

SEED = 20261008
random.seed(SEED)

MEM_WORDS = 1 << 17          # 1 MB image, byte addresses 0x00000 .. 0xFFFFF
DATA_BASE = 0x10000          # documents start here (descriptor queues below)
mem   = {}
docs  = []                   # (job_id, len, addr, digest)
sets  = {}                   # name -> (first_idx, count, desc_base)
data_ptr = DATA_BASE

EDGE = [0, 1, 7, 8, 9, 55, 56, 63, 64, 111, 112, 113, 119, 120, 127, 128, 129,
        239, 240, 255, 256, 257]

def put_bytes(addr, data):
    for i, b in enumerate(data):
        a = addr + i
        w = mem.get(a >> 3, 0)
        mem[a >> 3] = w | (b << (8 * (a & 7)))

def alloc(n, near_4k=False):
    global data_ptr
    if near_4k:                                     # start 8 bytes .. 120 bytes before a 4 KB boundary
        data_ptr = ((data_ptr + 4095) & ~4095) + 4096 - 8 * random.randint(1, 15)
    a = data_ptr
    data_ptr = (data_ptr + n + 7 + 8 * random.randint(0, 3)) & ~7
    assert data_ptr < MEM_WORDS * 8, "memory image full"
    return a

def add_set(name, lens, ids=None, desc_base=None, near_4k=False):
    first = len(docs)
    for i, n in enumerate(lens):
        msg = bytes(random.randrange(256) for _ in range(n))
        addr = alloc(n, near_4k)
        put_bytes(addr, msg)
        tail = (-n) % 8                                       # garbage after the last byte:
        put_bytes(addr + n, bytes(random.randrange(256) for _ in range(tail)))   # TKEEP must mask it
        jid = ids[i] if ids else (first + i) % 4000 + 1        # unique, fits 12-bit AWID
        docs.append((jid, n, addr, hashlib.sha512(msg).digest()))
    if desc_base is not None:
        for i in range(len(lens)):
            jid, n, addr, _ = docs[first + i]
            put_bytes(desc_base + 16 * i, (jid << 48 | n).to_bytes(8, "little") + addr.to_bytes(8, "little"))
    sets[name] = (first, len(lens), desc_base or 0)

def rand_lens(k, hi):
    return [random.randint(0, hi) for _ in range(k)]

# Descriptor queues (16 B per descriptor) live in 0x0000 .. 0xFFFF
add_set("PULL_MAIN", EDGE + rand_lens(150, 2048),          desc_base=0x0100)
add_set("PULL_SMALL", rand_lens(40, 64),                   desc_base=0x1000)
add_set("PULL_4K", [4096 + 8, 3000, 70000, 12345],         desc_base=0x1800, near_4k=True)
add_set("PUSH_MAIN", EDGE + rand_lens(80, 1500))
dup = [7, 7, 7, 9, 9, 7, 9, 7] * 3                          # repeated job IDs
add_set("PULL_DUP", [random.choice([200, 300, 700, 1100]) for _ in dup], ids=dup, desc_base=0x2000)
add_set("PULL_ERR", rand_lens(20, 1024),                   desc_base=0x2800)
add_set("PULL_AFTER", rand_lens(30, 1024),                 desc_base=0x3000)

with open("stress_mem.hex", "w") as f:
    for a in range(MEM_WORDS):
        f.write(f"{mem.get(a, 0):016x}\n")
with open("stress_docs.hex", "w") as f:
    for jid, n, addr, _ in docs:
        f.write(f"{jid:04x}{n:08x}{addr:08x}\n")
with open("stress_digest.hex", "w") as f:
    for *_, d in docs:
        f.write(d.hex() + "\n")
with open("stress_sets.svh", "w") as f:
    f.write("// Generated by gen_stress_vectors.py - do not edit\n")
    f.write(f"localparam NDOCS_ALL = {len(docs)};\n")
    for name, (first, cnt, base) in sets.items():
        f.write(f"localparam {name}_FIRST = {first}, {name}_CNT = {cnt}, {name}_DESC = 32'h{base:08x};\n")
    # first PULL_ERR data word: the testbench returns SLVERR for it
    e0, ec, _ = sets["PULL_ERR"]
    bad = next(d for d in docs[e0 + 5:e0 + ec] if d[1] >= 64)    # a data word that is really read
    f.write(f"localparam PULL_ERR_BAD_ADDR = 32'h{bad[2] + 32:08x};\n")

total = sum(d[1] for d in docs)
print(f"{len(docs)} documents, {total} bytes, data end 0x{data_ptr:x}")
for k, v in sets.items():
    print(f"  {k:11s} first={v[0]:4d} count={v[1]:4d} desc=0x{v[2]:x}")
