// ============================================================================
// tb_sha512_system.sv : Full-system self-checking testbench for SHA-512 Accelerator
//
// Tests:
//   1. Register & Version Sanity Check
//   2. PULL_MAIN  (172 docs) : DMA pull mode across edge cases & varied lengths
//   3. PULL_SMALL (40 docs)  : DMA pull mode with small docs (<= 64 B)
//   4. PULL_4K    (4 docs)   : DMA pull mode crossing 4KB boundaries & large docs
//   5. PUSH_MAIN  (102 docs) : Direct HPS push via AXI3 write slave input interface
//   6. PULL_DUP   (24 docs)  : Repeated job IDs in pull mode
//   7. PULL_ERR   (20 docs)  : DMA error injection (SLVERR on BAD_ADDR), IRQ & recovery
//   8. PULL_AFTER (30 docs)  : Post-recovery verification of accelerator
//
// Golden Model: Python hashlib via stress_digest.hex / stress_docs.hex / stress_mem.hex
// ============================================================================

`timescale 1ns/1ps

module tb_sha512_system;

    localparam N          = 12;
    localparam ID_W       = 12;
    localparam MEM_WORDS  = 1 << 17;   // 128K words = 1 MB (byte addresses 0x00000..0xFFFFF)
    localparam RES_BASE   = 32'h0008_0000;
    localparam RES_SLOTS  = 32'd512;

    // ------------------------------------------------------------------------
    // Test sets parameters generated by gen_stress_vectors.py
    // ------------------------------------------------------------------------
    `include "stress_sets.svh"

    // ------------------------------------------------------------------------
    // Clocks and Resets
    // ------------------------------------------------------------------------
    reg core_clk    = 0;
    reg h2f_axi_clk = 0;
    reg core_rst_n  = 0;
    reg h2f_axi_rst_n = 0;

    always #5 core_clk    = ~core_clk;       // 100 MHz
    always #5 h2f_axi_clk = ~h2f_axi_clk;   // 100 MHz

    // ------------------------------------------------------------------------
    // Emulated DDR3 Memory and Golden Test Vectors
    // ------------------------------------------------------------------------
    reg [63:0]  ddr3_mem   [0:MEM_WORDS-1];
    reg [79:0]  doc_info   [0:NDOCS_ALL-1];    // {job_id[15:0], len[31:0], addr[31:0]}
    reg [511:0] exp_digest [0:NDOCS_ALL-1];    // 512-bit expected hashlib digest

    // ------------------------------------------------------------------------
    // DUT Interface Signals
    // ------------------------------------------------------------------------
    // AXI-Lite Slave
    reg  [7:0]  s_axil_awaddr  = 0;
    reg         s_axil_awvalid = 0;
    wire        s_axil_awready;
    reg  [31:0] s_axil_wdata   = 0;
    reg  [3:0]  s_axil_wstrb   = 0;
    reg         s_axil_wvalid  = 0;
    wire        s_axil_wready;
    wire [1:0]  s_axil_bresp;
    wire        s_axil_bvalid;
    reg         s_axil_bready  = 0;
    reg  [7:0]  s_axil_araddr  = 0;
    reg         s_axil_arvalid = 0;
    wire        s_axil_arready;
    wire [31:0] s_axil_rdata;
    wire [1:0]  s_axil_rresp;
    wire        s_axil_rvalid;
    reg         s_axil_rready  = 0;

    // AXI3 Write Slave (Push Interface)
    reg  [ID_W-1:0] s_axi_awid    = 0;
    reg  [31:0]     s_axi_awaddr  = 0;
    reg  [3:0]      s_axi_awlen   = 0;
    reg  [2:0]      s_axi_awsize  = 0;
    reg  [1:0]      s_axi_awburst = 0;
    reg             s_axi_awvalid = 0;
    wire            s_axi_awready;
    reg  [ID_W-1:0] s_axi_wid     = 0;
    reg  [63:0]     s_axi_wdata   = 0;
    reg  [7:0]      s_axi_wstrb   = 0;
    reg             s_axi_wlast   = 0;
    reg             s_axi_wvalid  = 0;
    wire            s_axi_wready;
    wire [ID_W-1:0] s_axi_bid;
    wire [1:0]      s_axi_bresp;
    wire            s_axi_bvalid;
    reg             s_axi_bready  = 0;

    // AXI3 Read Master (DMA Reader)
    wire [11:0] m_rd_arid;
    wire [31:0] m_rd_araddr;
    wire [3:0]  m_rd_arlen;
    wire [2:0]  m_rd_arsize;
    wire [1:0]  m_rd_arburst;
    wire        m_rd_arvalid;
    wire        m_rd_arready;
    wire [11:0] m_rd_rid;
    wire [63:0] m_rd_rdata;
    wire [1:0]  m_rd_rresp;
    wire        m_rd_rlast;
    wire        m_rd_rvalid;
    wire        m_rd_rready;

    // AXI3 Write Master (Output Interface)
    wire [11:0] m_wr_awid;
    wire [31:0] m_wr_awaddr;
    wire [3:0]  m_wr_awlen;
    wire [2:0]  m_wr_awsize;
    wire [1:0]  m_wr_awburst;
    wire        m_wr_awvalid;
    wire        m_wr_awready;
    wire [11:0] m_wr_wid;
    wire [63:0] m_wr_wdata;
    wire [7:0]  m_wr_wstrb;
    wire        m_wr_wlast;
    wire        m_wr_wvalid;
    wire        m_wr_wready;
    wire [11:0] m_wr_bid;
    wire [1:0]  m_wr_bresp;
    wire        m_wr_bvalid;
    wire        m_wr_bready;

    wire fpga_irq;

    // ------------------------------------------------------------------------
    // DUT Instantiation
    // ------------------------------------------------------------------------
    sha512_accel_top #(
        .N(N),
        .ID_W(ID_W),
        .WD_TIMEOUT(32'd10_000_000)
    ) dut (
        .core_clk       (core_clk),
        .core_rst_n     (core_rst_n),
        .h2f_axi_clk    (h2f_axi_clk),
        .h2f_axi_rst_n  (h2f_axi_rst_n),

        .s_axil_awaddr  (s_axil_awaddr),
        .s_axil_awvalid (s_axil_awvalid),
        .s_axil_awready (s_axil_awready),
        .s_axil_wdata   (s_axil_wdata),
        .s_axil_wstrb   (s_axil_wstrb),
        .s_axil_wvalid  (s_axil_wvalid),
        .s_axil_wready  (s_axil_wready),
        .s_axil_bresp   (s_axil_bresp),
        .s_axil_bvalid  (s_axil_bvalid),
        .s_axil_bready  (s_axil_bready),
        .s_axil_araddr  (s_axil_araddr),
        .s_axil_arvalid (s_axil_arvalid),
        .s_axil_arready (s_axil_arready),
        .s_axil_rdata   (s_axil_rdata),
        .s_axil_rresp   (s_axil_rresp),
        .s_axil_rvalid  (s_axil_rvalid),
        .s_axil_rready  (s_axil_rready),

        .s_axi_awid     (s_axi_awid),
        .s_axi_awaddr   (s_axi_awaddr),
        .s_axi_awlen    (s_axi_awlen),
        .s_axi_awsize   (s_axi_awsize),
        .s_axi_awburst  (s_axi_awburst),
        .s_axi_awvalid  (s_axi_awvalid),
        .s_axi_awready  (s_axi_awready),
        .s_axi_wid      (s_axi_wid),
        .s_axi_wdata    (s_axi_wdata),
        .s_axi_wstrb    (s_axi_wstrb),
        .s_axi_wlast    (s_axi_wlast),
        .s_axi_wvalid   (s_axi_wvalid),
        .s_axi_wready   (s_axi_wready),
        .s_axi_bid      (s_axi_bid),
        .s_axi_bresp    (s_axi_bresp),
        .s_axi_bvalid   (s_axi_bvalid),
        .s_axi_bready   (s_axi_bready),

        .m_rd_arid      (m_rd_arid),
        .m_rd_araddr    (m_rd_araddr),
        .m_rd_arlen     (m_rd_arlen),
        .m_rd_arsize    (m_rd_arsize),
        .m_rd_arburst   (m_rd_arburst),
        .m_rd_arvalid   (m_rd_arvalid),
        .m_rd_arready   (m_rd_arready),
        .m_rd_rid       (m_rd_rid),
        .m_rd_rdata     (m_rd_rdata),
        .m_rd_rresp     (m_rd_rresp),
        .m_rd_rlast     (m_rd_rlast),
        .m_rd_rvalid    (m_rd_rvalid),
        .m_rd_rready    (m_rd_rready),

        .m_wr_awid      (m_wr_awid),
        .m_wr_awaddr    (m_wr_awaddr),
        .m_wr_awlen     (m_wr_awlen),
        .m_wr_awsize    (m_wr_awsize),
        .m_wr_awburst   (m_wr_awburst),
        .m_wr_awvalid   (m_wr_awvalid),
        .m_wr_awready   (m_wr_awready),
        .m_wr_wid       (m_wr_wid),
        .m_wr_wdata     (m_wr_wdata),
        .m_wr_wstrb     (m_wr_wstrb),
        .m_wr_wlast     (m_wr_wlast),
        .m_wr_wvalid    (m_wr_wvalid),
        .m_wr_wready    (m_wr_wready),
        .m_wr_bid       (m_wr_bid),
        .m_wr_bresp     (m_wr_bresp),
        .m_wr_bvalid    (m_wr_bvalid),
        .m_wr_bready    (m_wr_bready),

        .fpga_irq       (fpga_irq)
    );

    // ------------------------------------------------------------------------
    // DDR3 Memory Model: AXI3 Read Slave (servicing DMA Reader on core_clk)
    // ------------------------------------------------------------------------
    reg [11:0] rd_id_q       = 0;
    reg [31:0] rd_addr_q     = 0;
    reg [4:0]  rd_len_q      = 0;
    reg [4:0]  rd_cnt_q      = 0;
    reg        rd_active     = 0;
    reg        inject_dma_err = 0;

    reg        m_rd_rvalid_r = 0;
    reg [63:0] m_rd_rdata_r  = 0;
    reg [1:0]  m_rd_rresp_r  = 0;
    reg        m_rd_rlast_r  = 0;
    reg [11:0] m_rd_rid_r    = 0;

    assign m_rd_arready = !rd_active;
    assign m_rd_rvalid  = m_rd_rvalid_r;
    assign m_rd_rdata   = m_rd_rdata_r;
    assign m_rd_rresp   = m_rd_rresp_r;
    assign m_rd_rlast   = m_rd_rlast_r;
    assign m_rd_rid     = m_rd_rid_r;

    always @(posedge core_clk or negedge core_rst_n) begin
        if (!core_rst_n || !dut.core_dp_rst_n) begin
            rd_active     <= 1'b0;
            rd_id_q       <= 12'd0;
            rd_addr_q     <= 32'd0;
            rd_len_q      <= 5'd0;
            rd_cnt_q      <= 5'd0;
            m_rd_rvalid_r <= 1'b0;
            m_rd_rdata_r  <= 64'd0;
            m_rd_rresp_r  <= 2'b00;
            m_rd_rlast_r  <= 1'b0;
            m_rd_rid_r    <= 12'd0;
        end else begin
            if (m_rd_arvalid && m_rd_arready) begin
                rd_active     <= 1'b1;
                rd_id_q       <= m_rd_arid;
                rd_addr_q     <= m_rd_araddr;
                rd_len_q      <= {1'b0, m_rd_arlen} + 5'd1;
                rd_cnt_q      <= 5'd0;
                m_rd_rvalid_r <= 1'b1;
                m_rd_rid_r    <= m_rd_arid;
                m_rd_rdata_r  <= ddr3_mem[(m_rd_araddr >> 3) & (MEM_WORDS-1)];
                m_rd_rlast_r  <= (m_rd_arlen == 4'd0);
                if (inject_dma_err && (m_rd_araddr == PULL_ERR_BAD_ADDR))
                    m_rd_rresp_r <= 2'b10; // SLVERR
                else
                    m_rd_rresp_r <= 2'b00; // OKAY
            end else if (m_rd_rvalid_r && m_rd_rready) begin
                if (rd_cnt_q + 5'd1 >= rd_len_q) begin
                    rd_active     <= 1'b0;
                    m_rd_rvalid_r <= 1'b0;
                    m_rd_rlast_r  <= 1'b0;
                end else begin
                    rd_cnt_q      <= rd_cnt_q + 5'd1;
                    m_rd_rvalid_r <= 1'b1;
                    m_rd_rdata_r  <= ddr3_mem[((rd_addr_q >> 3) + (rd_cnt_q + 5'd1)) & (MEM_WORDS-1)];
                    m_rd_rlast_r  <= (rd_cnt_q + 5'd2 >= rd_len_q);
                    if (inject_dma_err && ((rd_addr_q + ((rd_cnt_q + 5'd1) << 3)) == PULL_ERR_BAD_ADDR))
                        m_rd_rresp_r <= 2'b10; // SLVERR
                    else
                        m_rd_rresp_r <= 2'b00; // OKAY
                end
            end
        end
    end

    // ------------------------------------------------------------------------
    // DDR3 Memory Model: AXI3 Write Slave (servicing Output IF on h2f_axi_clk)
    // ------------------------------------------------------------------------
    reg [11:0] wr_id_q     = 0;
    reg [31:0] wr_addr_q   = 0;
    reg [3:0]  wr_beat_cnt = 0;
    reg        wr_aw_done  = 0;
    reg        wr_bvalid_r = 0;
    reg [11:0] wr_bid_r    = 0;

    assign m_wr_awready = !wr_aw_done;
    assign m_wr_wready  = wr_aw_done && !wr_bvalid_r;
    assign m_wr_bvalid  = wr_bvalid_r;
    assign m_wr_bresp   = 2'b00;
    assign m_wr_bid     = wr_bid_r;

    reg [15:0]  cap_job   = 0;
    reg [511:0] cap_dig   = 0;
    reg         cap_valid = 0;

    always @(posedge h2f_axi_clk or negedge h2f_axi_rst_n) begin
        if (!h2f_axi_rst_n || !dut.axi_dp_rst_n) begin
            wr_aw_done  <= 1'b0;
            wr_bvalid_r <= 1'b0;
            wr_beat_cnt <= 4'd0;
            wr_id_q     <= 12'd0;
            wr_addr_q   <= 32'd0;
            wr_bid_r    <= 12'd0;
            cap_job     <= 16'd0;
            cap_dig     <= 512'd0;
            cap_valid   <= 1'b0;
        end else begin
            cap_valid <= 1'b0;

            if (m_wr_awvalid && m_wr_awready) begin
                wr_aw_done  <= 1'b1;
                wr_id_q     <= m_wr_awid;
                wr_addr_q   <= m_wr_awaddr;
                wr_beat_cnt <= 4'd0;
            end

            if (m_wr_wvalid && m_wr_wready) begin
                ddr3_mem[((wr_addr_q >> 3) + wr_beat_cnt) & (MEM_WORDS-1)] <= m_wr_wdata;

                if (wr_beat_cnt == 4'd0) begin
                    cap_job <= m_wr_wdata[15:0];
                    cap_dig <= 512'd0;
                end else begin
                    cap_dig <= {cap_dig[447:0], m_wr_wdata};
                end

                if (m_wr_wlast) begin
                    wr_aw_done  <= 1'b0;
                    wr_bvalid_r <= 1'b1;
                    wr_bid_r    <= wr_id_q;
                    cap_valid   <= 1'b1;
                end else begin
                    wr_beat_cnt <= wr_beat_cnt + 4'd1;
                end
            end

            if (m_wr_bvalid && m_wr_bready) begin
                wr_bvalid_r <= 1'b0;
            end
        end
    end

    // ------------------------------------------------------------------------
    // Result Collection Queue (stores every completed result written to DDR3)
    // ------------------------------------------------------------------------
    reg [15:0]  res_q_job [0:1023];
    reg [511:0] res_q_dig [0:1023];
    integer     res_wr_ptr = 0;

    always @(posedge h2f_axi_clk) begin
        if (h2f_axi_rst_n && cap_valid) begin
            res_q_job[res_wr_ptr] <= cap_job;
            res_q_dig[res_wr_ptr] <= cap_dig;
            res_wr_ptr <= res_wr_ptr + 1;
        end
    end

    // ------------------------------------------------------------------------
    // AXI-Lite Master Tasks
    // ------------------------------------------------------------------------
    task axil_write(input [7:0] addr, input [31:0] data);
        begin
            @(posedge core_clk);
            s_axil_awaddr  <= addr;
            s_axil_awvalid <= 1'b1;
            s_axil_wdata   <= data;
            s_axil_wstrb   <= 4'hF;
            s_axil_wvalid  <= 1'b1;
            s_axil_bready  <= 1'b1;

            while (!(s_axil_awvalid && s_axil_awready)) @(posedge core_clk);
            s_axil_awvalid <= 1'b0;

            while (!(s_axil_wvalid && s_axil_wready)) @(posedge core_clk);
            s_axil_wvalid  <= 1'b0;

            while (!s_axil_bvalid) @(posedge core_clk);
            @(posedge core_clk);
            s_axil_bready  <= 1'b0;
        end
    endtask

    task axil_read(input [7:0] addr, output [31:0] data);
        begin
            @(posedge core_clk);
            s_axil_araddr  <= addr;
            s_axil_arvalid <= 1'b1;
            s_axil_rready  <= 1'b1;

            while (!(s_axil_arvalid && s_axil_arready)) @(posedge core_clk);
            s_axil_arvalid <= 1'b0;

            while (!s_axil_rvalid) @(posedge core_clk);
            data = s_axil_rdata;
            @(posedge core_clk);
            s_axil_rready  <= 1'b0;
        end
    endtask

    // ------------------------------------------------------------------------
    // AXI3 Push Master Task (HPS DMA writing via s_axi)
    // ------------------------------------------------------------------------
    task push_doc(input [15:0] jid, input [31:0] doc_len, input [31:0] doc_addr);
        integer nw, w_idx, burst_len, b, rem;
        reg [63:0] wdata;
        reg [7:0]  wstrb;
        reg is_last;
        begin
            nw = (doc_len == 0) ? 1 : ((doc_len + 7) >> 3);
            w_idx = 0;
            while (w_idx < nw) begin
                burst_len = ((nw - w_idx) > 16) ? 16 : (nw - w_idx);
                is_last   = (w_idx + burst_len == nw);

                // AW channel: bit 24 indicates the final burst of the document
                @(posedge h2f_axi_clk);
                s_axi_awid    <= jid[ID_W-1:0];
                s_axi_awaddr  <= (is_last ? 32'h0100_0000 : 32'h0000_0000) | (doc_addr + (w_idx << 3));
                s_axi_awlen   <= burst_len - 1;
                s_axi_awsize  <= 3'd3;
                s_axi_awburst <= 2'b01;
                s_axi_awvalid <= 1'b1;

                @(posedge h2f_axi_clk);
                while (!s_axi_awready) @(posedge h2f_axi_clk);
                s_axi_awvalid <= 1'b0;

                // W channel
                for (b = 0; b < burst_len; b = b + 1) begin
                    if (doc_len == 0) begin
                        wdata = 64'd0;
                        wstrb = 8'h00;
                    end else begin
                        wdata = ddr3_mem[((doc_addr >> 3) + w_idx + b) & (MEM_WORDS-1)];
                        if ((w_idx + b == nw - 1) && (doc_len[2:0] != 3'd0)) begin
                            rem   = doc_len[2:0];
                            wstrb = (8'd1 << rem) - 8'd1;
                        end else begin
                            wstrb = 8'hFF;
                        end
                    end

                    s_axi_wid    <= jid[ID_W-1:0];
                    s_axi_wdata  <= wdata;
                    s_axi_wstrb  <= wstrb;
                    s_axi_wlast  <= (b == burst_len - 1);
                    s_axi_wvalid <= 1'b1;

                    @(posedge h2f_axi_clk);
                    while (!s_axi_wready) @(posedge h2f_axi_clk);
                    s_axi_wvalid <= 1'b0;
                    s_axi_wlast  <= 1'b0;
                end

                // B channel
                s_axi_bready <= 1'b1;
                @(posedge h2f_axi_clk);
                while (!s_axi_bvalid) @(posedge h2f_axi_clk);
                s_axi_bready <= 1'b0;

                w_idx = w_idx + burst_len;
            end
        end
    endtask

    // ------------------------------------------------------------------------
    // Result Verification Task
    // ------------------------------------------------------------------------
    integer test_errors = 0;

    task wait_and_verify_set(
        input [127:0] set_name,
        input integer first_doc,
        input integer count,
        input integer start_ptr
    );
        integer timeout;
        integer r, d, found, all_ok;
        reg [511:0] matched;
        reg [31:0]  st_val;
        begin
            matched = 512'd0;
            timeout = 0;

            // Wait for all expected results to arrive
            while ((res_wr_ptr < start_ptr + count) && (timeout < 500000)) begin
                @(posedge core_clk);
                timeout = timeout + 1;
            end

            if (res_wr_ptr < start_ptr + count) begin
                $display("ERROR [%0s]: TIMEOUT! Received %0d/%0d results after %0d cycles",
                         set_name, res_wr_ptr - start_ptr, count, timeout);
                test_errors = test_errors + 1;
            end

            // Wait a few cycles for core manager & system FSM to idle
            repeat (30) @(posedge core_clk);

            axil_read(8'h04, st_val);
            $display("  STATUS after %0s: 0x%08x (idle=%b, err=%b, done=%b, busy=%b)",
                     set_name, st_val, st_val[3], st_val[2], st_val[1], st_val[0]);

            // Match each received result to an expected document
            for (r = 0; r < (res_wr_ptr - start_ptr); r = r + 1) begin
                found = 0;
                for (d = 0; d < count; d = d + 1) begin
                    if (!found && !matched[d] &&
                        (doc_info[first_doc + d][79:64] == res_q_job[start_ptr + r]) &&
                        (exp_digest[first_doc + d] === res_q_dig[start_ptr + r])) begin
                        matched[d] = 1'b1;
                        found = 1;
                    end
                end
                if (!found) begin
                    $display("FAIL [%0s]: Received unexpected result %0d (job %0d)",
                             set_name, r, res_q_job[start_ptr + r]);
                    $display("       Got digest: %0128x", res_q_dig[start_ptr + r]);
                    test_errors = test_errors + 1;
                end
            end

            // Check if any expected document was missed
            all_ok = 1;
            for (d = 0; d < count; d = d + 1) begin
                if (!matched[d]) begin
                    all_ok = 0;
                    $display("FAIL [%0s]: Missing result for doc %0d (job %0d)",
                             set_name, first_doc + d, doc_info[first_doc + d][79:64]);
                    $display("       Expected digest: %0128x", exp_digest[first_doc + d]);
                    test_errors = test_errors + 1;
                end
            end

            if (all_ok && (res_wr_ptr >= start_ptr + count)) begin
                $display("PASS: %0s (%0d documents verified)", set_name, count);
            end
        end
    endtask

    // ------------------------------------------------------------------------
    // Main Test Sequence
    // ------------------------------------------------------------------------
    integer i, ptr_mark, err_timeout;
    reg [31:0] rdata;

    initial begin
        // Optional VCD dump if requested via +dump
        if ($test$plusargs("dump")) begin
            $dumpfile("tb_sha512_system.vcd");
            $dumpvars(0, tb_sha512_system);
        end

        $display("==========================================================");
        $display("  SHA-512 SYSTEM ACCELERATOR SELF-CHECKING TESTBENCH      ");
        $display("==========================================================");

        // Load memory image, document table, and golden digests
        $readmemh("stress_mem.hex", ddr3_mem);
        $readmemh("stress_docs.hex", doc_info);
        $readmemh("stress_digest.hex", exp_digest);
        $display("[INFO] Loaded %0d document vectors and DDR3 image", NDOCS_ALL);

        // Reset assertion
        core_rst_n    = 0;
        h2f_axi_rst_n = 0;
        repeat (10) @(posedge core_clk);
        core_rst_n    = 1;
        h2f_axi_rst_n = 1;
        repeat (30) @(posedge core_clk);

        // --------------------------------------------------------------------
        // Test 1: Register Bank & Version Sanity Check
        // --------------------------------------------------------------------
        $display("\n--- Test 1: Register Bank & Version Sanity Check ---");
        axil_read(8'h1C, rdata); // A_VERSION
        $display("  Read VERSION = 0x%08x (expected 0x00010001)", rdata);
        if (rdata !== 32'h0001_0001) begin
            $display("FAIL: VERSION mismatch!");
            test_errors = test_errors + 1;
        end else begin
            $display("PASS: Version register verified");
        end

        axil_read(8'h04, rdata); // A_STATUS
        $display("  Initial STATUS = 0x%08x (idle=%b, err=%b, done=%b, busy=%b)",
                 rdata, rdata[3], rdata[2], rdata[1], rdata[0]);

        // Configure common result buffer
        axil_write(8'h28, RES_BASE);   // A_RES_BASE
        axil_write(8'h2C, RES_SLOTS);  // A_RES_SLOTS
        axil_write(8'h08, 32'h0000_0FFF); // Enable all 12 cores

        // --------------------------------------------------------------------
        // Test 2: PULL_MAIN (172 docs) - Edge cases & varied lengths
        // --------------------------------------------------------------------
        $display("\n--- Test 2: PULL_MAIN (%0d docs) ---", PULL_MAIN_CNT);
        ptr_mark = res_wr_ptr;
        axil_write(8'h14, PULL_MAIN_DESC); // JOB_BASE
        axil_write(8'h18, PULL_MAIN_CNT);  // JOB_COUNT
        axil_write(8'h00, 32'h0000_00C1);  // START=1, CORE_COUNT=12
        wait_and_verify_set("PULL_MAIN", PULL_MAIN_FIRST, PULL_MAIN_CNT, ptr_mark);

        // --------------------------------------------------------------------
        // Test 3: PULL_SMALL (40 docs) - Short messages <= 64 bytes
        // --------------------------------------------------------------------
        $display("\n--- Test 3: PULL_SMALL (%0d docs) ---", PULL_SMALL_CNT);
        ptr_mark = res_wr_ptr;
        axil_write(8'h14, PULL_SMALL_DESC);
        axil_write(8'h18, PULL_SMALL_CNT);
        axil_write(8'h00, 32'h0000_00C1);
        wait_and_verify_set("PULL_SMALL", PULL_SMALL_FIRST, PULL_SMALL_CNT, ptr_mark);

        // --------------------------------------------------------------------
        // Test 4: PULL_4K (4 docs) - 4KB boundary crossings & large documents
        // --------------------------------------------------------------------
        $display("\n--- Test 4: PULL_4K (%0d docs) ---", PULL_4K_CNT);
        ptr_mark = res_wr_ptr;
        axil_write(8'h14, PULL_4K_DESC);
        axil_write(8'h18, PULL_4K_CNT);
        axil_write(8'h00, 32'h0000_00C1);
        wait_and_verify_set("PULL_4K", PULL_4K_FIRST, PULL_4K_CNT, ptr_mark);

        // --------------------------------------------------------------------
        // Test 5: PUSH_MAIN (102 docs) - Direct HPS push via s_axi
        // --------------------------------------------------------------------
        $display("\n--- Test 5: PUSH_MAIN (%0d docs) ---", PUSH_MAIN_CNT);
        ptr_mark = res_wr_ptr;
        axil_write(8'h14, 32'd0);          // JOB_BASE = 0 (PUSH mode)
        axil_write(8'h18, PUSH_MAIN_CNT);  // JOB_COUNT
        axil_write(8'h00, 32'h0000_00C1);  // START=1

        // Stream documents into s_axi input interface
        for (i = 0; i < PUSH_MAIN_CNT; i = i + 1) begin
            push_doc(doc_info[PUSH_MAIN_FIRST + i][79:64],
                     doc_info[PUSH_MAIN_FIRST + i][63:32],
                     doc_info[PUSH_MAIN_FIRST + i][31:0]);
        end
        wait_and_verify_set("PUSH_MAIN", PUSH_MAIN_FIRST, PUSH_MAIN_CNT, ptr_mark);

        // --------------------------------------------------------------------
        // Test 6: PULL_DUP (24 docs) - Duplicate job IDs
        // --------------------------------------------------------------------
        $display("\n--- Test 6: PULL_DUP (%0d docs) ---", PULL_DUP_CNT);
        ptr_mark = res_wr_ptr;
        axil_write(8'h14, PULL_DUP_DESC);
        axil_write(8'h18, PULL_DUP_CNT);
        axil_write(8'h00, 32'h0000_00C1);
        wait_and_verify_set("PULL_DUP", PULL_DUP_FIRST, PULL_DUP_CNT, ptr_mark);

        // --------------------------------------------------------------------
        // Test 7: PULL_ERR (20 docs) - SLVERR injection, IRQ & reset recovery
        // --------------------------------------------------------------------
        $display("\n--- Test 7: PULL_ERR (Error injection & recovery) ---");
        inject_dma_err = 1'b1;
        axil_write(8'h14, PULL_ERR_DESC);
        axil_write(8'h18, PULL_ERR_CNT);
        axil_write(8'h0C, 32'h0000_0007);  // IRQ_EN: enable all interrupt sources
        axil_write(8'h00, 32'h0000_00C9);  // START=1, CORE_COUNT=12, IRQ_GLOBAL_EN=1

        // Wait for system FSM to detect DMA error and set STATUS[ERROR]
        err_timeout = 0;
        rdata = 0;
        while ((rdata[2] == 1'b0) && (err_timeout < 50000)) begin
            @(posedge core_clk);
            err_timeout = err_timeout + 1;
            if (err_timeout % 50 == 0) begin
                axil_read(8'h04, rdata);
            end
        end

        if (rdata[2] == 1'b1) begin
            $display("PASS: STATUS[ERROR] asserted (STATUS=0x%08x)", rdata);
        end else begin
            $display("FAIL: STATUS[ERROR] was not asserted!");
            test_errors = test_errors + 1;
        end

        // Check ERROR_FLAGS register (0x24): bit 0 should be set
        axil_read(8'h24, rdata);
        $display("  ERROR_FLAGS = 0x%08x (expected bit 0 = 1)", rdata);
        if (rdata[0] !== 1'b1) begin
            $display("FAIL: ERROR_FLAGS[0] not set!");
            test_errors = test_errors + 1;
        end

        // Check IRQ_STATUS register (0x10): bit 1 should be set
        axil_read(8'h10, rdata);
        $display("  IRQ_STATUS  = 0x%08x (expected bit 1 = 1)", rdata);
        if (rdata[1] !== 1'b1) begin
            $display("FAIL: IRQ_STATUS[1] error bit not set!");
            test_errors = test_errors + 1;
        end

        if (fpga_irq !== 1'b1) begin
            $display("FAIL: fpga_irq line not asserted!");
            test_errors = test_errors + 1;
        end else begin
            $display("PASS: fpga_irq asserted correctly");
        end

        // Recover from error
        inject_dma_err = 1'b0;
        $display("  Executing soft reset & clearing error/interrupt flags...");
        axil_write(8'h00, 32'h0000_0002); // CTRL[RESET] = 1
        repeat (25) @(posedge core_clk);
        axil_write(8'h24, 32'h0000_0007); // W1C ERROR_FLAGS
        axil_write(8'h10, 32'h0000_0007); // W1C IRQ_STATUS

        // Verify recovery to IDLE state
        axil_read(8'h04, rdata);
        $display("  STATUS after reset = 0x%08x (idle=%b, err=%b)", rdata, rdata[3], rdata[2]);
        if (rdata[3] === 1'b1 && rdata[2] === 1'b0) begin
            $display("PASS: Accelerator returned to clean IDLE state after reset");
        end else begin
            $display("FAIL: Accelerator failed to recover to IDLE (STATUS=0x%08x)", rdata);
            test_errors = test_errors + 1;
        end

        // --------------------------------------------------------------------
        // Test 8: PULL_AFTER (30 docs) - Verification after error recovery
        // --------------------------------------------------------------------
        $display("\n--- Test 8: PULL_AFTER (%0d docs post-recovery) ---", PULL_AFTER_CNT);
        ptr_mark = res_wr_ptr;
        axil_write(8'h28, RES_BASE);
        axil_write(8'h2C, RES_SLOTS);
        axil_write(8'h08, 32'h0000_0FFF);
        axil_write(8'h14, PULL_AFTER_DESC);
        axil_write(8'h18, PULL_AFTER_CNT);
        axil_write(8'h00, 32'h0000_00C1);
        wait_and_verify_set("PULL_AFTER", PULL_AFTER_FIRST, PULL_AFTER_CNT, ptr_mark);

        // --------------------------------------------------------------------
        // Final Results Summary
        // --------------------------------------------------------------------
        $display("\n==========================================================");
        if (test_errors == 0) begin
            $display("  >>> ALL %0d SYSTEM STRESS TESTS PASSED SUCCESSFULLY! <<<", NDOCS_ALL);
        end else begin
            $display("  >>> FAILED WITH %0d ERROR(S)! <<<", test_errors);
        end
        $display("==========================================================");

        $finish;
    end

endmodule
